// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizhkGpJVLF_3aDeqEyno1VYN3cZFbIII',
    appId: '1:868234632104:web:91f5e8c504e648259bdb9d',
    messagingSenderId: '868234632104',
    projectId: 'edu-app-c4a2f',
    authDomain: 'edu-app-c4a2f.firebaseapp.com',
    storageBucket: 'edu-app-c4a2f.appspot.com',
    measurementId: 'G-8YNKGFFJWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtj-Ebe1wfx35olfpUl1xk_-WMUMT79pc',
    appId: '1:868234632104:android:0d1c9480067b638c9bdb9d',
    messagingSenderId: '868234632104',
    projectId: 'edu-app-c4a2f',
    storageBucket: 'edu-app-c4a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5kBzQgKR69P2TZ9wAr_bCKMSC0WFKz6g',
    appId: '1:868234632104:ios:187d30ca222725f29bdb9d',
    messagingSenderId: '868234632104',
    projectId: 'edu-app-c4a2f',
    storageBucket: 'edu-app-c4a2f.appspot.com',
    iosBundleId: 'com.example.eduApp',
  );
}
